### ISSUE TITLE
Improve UCSC update function performance

### ISSUE THREAD

**Issue by bjohnson8949** [bjohnson8949/LOKI#3]
UCSC processing takes a long time and should look if we can do this in parallel

**Comment by van-truong** [comment]
We looked at Brandon's timed log output

Saw that UCSC ECR takes 8 hrs to process & compact/compile into SQLite schema
Total LOKI processing time for all sources is 12 hrs 

Li agrees that working on this will be the biggest win

**Comment by bjohnson8949** [comment]
Going to need to find a better method for SELECT last_insert_rowid() in sqllite because it can't be trusted in threaded operations. 

Docs: https://www.sqlite.org/c3ref/last_insert_rowid.html
