### ISSUE TITLE
Download to separate directories

### ISSUE THREAD

**Issue by bjohnson8949** [bjohnson8949/LOKI#5]
I removed code that put it in separate directories because it was breaking around threads. This limits file names being different from each source. To ensure different file names this should be patched for in the future. Best method is going to be changing downloads to accept the path to download files.

**Comment by XueqiongLi** [comment]
I tried other ways but ended up transferring hardcoded absolute path to downloading & processing functions rather than changing working directory, which always causing "wrong path" issue. [Corresponding commit](https://github.com/bjohnson8949/LOKI/commit/122c3a077e97ed96bc73f9ba1977ea1b65192419)
